steps:
  # Step 1: Generate random suffix, zip the workspace, and save the filename
  - name: 'ubuntu'
    id: 'zip-workspace'
    script: |
      #!/usr/bin/env bash
      
      apt-get update && apt-get install zip openssl -y
      RANDOM_SUFFIX=$(openssl rand -hex 2)
      FILE_NAME="pr-workspace-${RANDOM_SUFFIX}.zip"
      echo "Zipping code into ${FILE_NAME}..."
      zip -r ${FILE_NAME} . -x "*.zip"
      echo ${FILE_NAME} > /workspace/generated_filename.txt

  # Step 2: Read the filename and upload it to GCS
  - name: 'gcr.io/cloud-builders/gsutil'
    id: 'upload-to-gcs'
    entrypoint: 'bash'
    args: 
      - '-c'
      - |
        FILE_NAME=$(cat /workspace/generated_filename.txt)
        echo "Uploading ${FILE_NAME} to gs://${_BUCKET_NAME}/..."
        gsutil cp ${FILE_NAME} gs://${_BUCKET_NAME}/${FILE_NAME}
        rm /workspace/generated_filename.txt

substitutions:
  _BUCKET_NAME: 'dev-connect-poc'

serviceAccount: 'projects/$PROJECT_ID/serviceAccounts/dev-connect-poc-sa@$PROJECT_ID.iam.gserviceaccount.com'

logsBucket: 'dev-connect-poc-logs'
